# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )
    include_details: Optional[bool] = Field(
        False,
        description="Whether or not to include observation details",
        title="Include Details",
    )
    include_subjectsource_details: Optional[bool] = Field(
        False,
        description="Whether or not to include subject source details",
        title="Include Subjectsource Details",
    )


class SubjectGroup(BaseModel):
    subject_obs: Optional[SubjectObs] = Field(None, title="")


class SqlQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: Optional[str] = Field(
        "",
        description="SQL query string to apply to the DataFrame. Leaves it unchanged when the field is emptyUse 'df' as the table name in the query.",
        title="Query",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="Optional list of column names to include in the SQL query context. If specified, only these columns will be available in the 'df' table for querying. Use this to exclude columns with unsupported data types (list, dict) that cannot be stored in SQLite. If not specified, all columns are included.",
        title="Columns",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistTracks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["csv"], description="The output format", title="Filetypes"
    )
    filename_prefix: Optional[str] = Field(
        "subject_tracks",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class SkipMapGeneration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skip: Optional[bool] = Field(
        False,
        description="Skip generating maps for subject tracks. Recommended for large datasets to improve performance.",
        title="Skip",
    )


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class GenerateMaps(BaseModel):
    skip_map_generation: Optional[SkipMapGeneration] = Field(
        None, title="Skip Map Generation"
    )
    base_map_defs: Optional[BaseMapDefs] = Field(None, title="Map Base Layers")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class BoundingBox(BaseModel):
    min_y: Optional[float] = Field(-90.0, title="Min Latitude")
    max_y: Optional[float] = Field(90.0, title="Max Latitude")
    min_x: Optional[float] = Field(-180.0, title="Min Longitude")
    max_x: Optional[float] = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class RenameColumn(BaseModel):
    original_name: str = Field(..., title="Original Name")
    new_name: str = Field(..., title="New Name")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class FilterObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: Optional[BoundingBox] = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: Optional[List[Coordinate]] = Field(
        [],
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )


class SubjectTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class CustomizeColumns(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    drop_columns: Optional[List[str]] = Field(
        [], description="List of columns to drop.", title="Drop Columns"
    )
    retain_columns: Optional[List[str]] = Field(
        [],
        description="List of columns to retain with the order specified by the list.\n                        Keep all the columns if the list is empty.",
        title="Retain Columns",
    )
    rename_columns: Optional[List[RenameColumn]] = Field(
        {}, description="Dictionary of columns to rename.", title="Rename Columns"
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class ProcessObservations(BaseModel):
    filter_obs: Optional[FilterObs] = Field(
        None, title="Filter Observation Relocations"
    )
    subject_traj: Optional[SubjectTraj] = Field(None, title="Trajectory Segment Filter")
    customize_columns: Optional[CustomizeColumns] = Field(None, title="Process Columns")
    sql_query: Optional[SqlQuery] = Field(None, title="Apply SQL Query")
    groupers: Optional[Groupers] = Field(None, title="Group Data")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: Optional[ErClientName] = Field(None, title="Data Source")
    Subject_Group: Optional[SubjectGroup] = Field(
        None, alias="Subject Group", description="Choose a subject group to analyze"
    )
    Process_Observations: Optional[ProcessObservations] = Field(
        None,
        alias="Process Observations",
        description="Process observations by applying filters, SQL queries, etc. Note that the data here includes all the columns from the previous steps and the normalized subject/observation details.",
    )
    persist_tracks: Optional[PersistTracks] = Field(
        None, title="Persist Subject Trajectories"
    )
    Generate_Maps: Optional[GenerateMaps] = Field(
        None,
        alias="Generate Maps",
        description="Generate maps to visualize the subject trajectories.",
    )
