# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Download Subjects
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.warning import (
    mixed_subtype_warning as mixed_subtype_warning,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone Selection

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

subject_obs_params = dict(
    subject_group_name=...,
    include_details=...,
    include_subjectsource_details=...,
)

# %%
# call the task


subject_obs = (
    get_subjectgroup_observations.set_task_instance_id("subject_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=False,
        **subject_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Warn if mixed subtype

# %%
# parameters

warn_if_mixed_subtype_params = dict()

# %%
# call the task


warn_if_mixed_subtype = (
    mixed_subtype_warning.set_task_instance_id("warn_if_mixed_subtype")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(subject_obs=subject_obs, **warn_if_mixed_subtype_params)
    .call()
)


# %% [markdown]
# ## Convert to timezone

# %%
# parameters

convert_to_user_timezone_params = dict()

# %%
# call the task


convert_to_user_timezone = (
    convert_values_to_timezone.set_task_instance_id("convert_to_user_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_obs,
        timezone=get_timezone,
        columns=["fixtime"],
        **convert_to_user_timezone_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Extra

# %%
# parameters

drop_extra_prefix_params = dict()

# %%
# call the task


drop_extra_prefix = (
    drop_column_prefix.set_task_instance_id("drop_extra_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_to_user_timezone,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_extra_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Observation Relocations

# %%
# parameters

filter_obs_params = dict(
    bounding_box=...,
    filter_point_coords=...,
)

# %%
# call the task


filter_obs = (
    apply_reloc_coord_filter.set_task_instance_id("filter_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_extra_prefix,
        roi_gdf=None,
        roi_name=None,
        reset_index=False,
        **filter_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Trajectory Segment Filter

# %%
# parameters

subject_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


subject_traj = (
    relocations_to_trajectory.set_task_instance_id("subject_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=filter_obs, **subject_traj_params)
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Extra

# %%
# parameters

drop_extra_prefix_traj_params = dict()

# %%
# call the task


drop_extra_prefix_traj = (
    drop_column_prefix.set_task_instance_id("drop_extra_prefix_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_traj,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_extra_prefix_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Internally Process Columns

# %%
# parameters

customize_columns_internally_params = dict()

# %%
# call the task


customize_columns_internally = (
    map_columns.set_task_instance_id("customize_columns_internally")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_extra_prefix_traj,
        rename_columns={},
        drop_columns=["id"],
        retain_columns=[],
        **customize_columns_internally_params,
    )
    .call()
)


# %% [markdown]
# ## Process Columns

# %%
# parameters

customize_columns_params = dict(
    drop_columns=...,
    retain_columns=...,
    rename_columns=...,
)

# %%
# call the task


customize_columns = (
    map_columns.set_task_instance_id("customize_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=customize_columns_internally, **customize_columns_params)
    .call()
)


# %% [markdown]
# ## Apply SQL Query

# %%
# parameters

sql_query_params = dict(
    query=...,
    columns=...,
)

# %%
# call the task


sql_query = (
    apply_sql_query.set_task_instance_id("sql_query")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=customize_columns, **sql_query_params)
    .call()
)


# %% [markdown]
# ## Group Data

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Add temporal index to observations

# %%
# parameters

obs_add_temporal_index_params = dict()

# %%
# call the task


obs_add_temporal_index = (
    add_temporal_index.set_task_instance_id("obs_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=sql_query,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **obs_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Split Trajectory by Group

# %%
# parameters

split_traj_groups_params = dict()

# %%
# call the task


split_traj_groups = (
    split_groups.set_task_instance_id("split_traj_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=obs_add_temporal_index, groupers=groupers, **split_traj_groups_params)
    .call()
)


# %% [markdown]
# ## Persist Subject Trajectories

# %%
# parameters

persist_tracks_params = dict(
    filename=...,
    filetypes=...,
    filename_prefix=...,
)

# %%
# call the task


persist_tracks = (
    persist_df_wrapper.set_task_instance_id("persist_tracks")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        **persist_tracks_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_traj_groups)
)


# %% [markdown]
# ## Skip Map Generation

# %%
# parameters

skip_map_generation_params = dict(
    skip=...,
)

# %%
# call the task


skip_map_generation = (
    maybe_skip_df.set_task_instance_id("skip_map_generation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**skip_map_generation_params)
    .mapvalues(argnames=["df"], argvalues=split_traj_groups)
)


# %% [markdown]
# ## Set Trajectory Map Title

# %%
# parameters

set_traj_map_title_params = dict()

# %%
# call the task


set_traj_map_title = (
    set_string_var.set_task_instance_id("set_traj_map_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Subject Group Trajectory Map", **set_traj_map_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Apply Color to Trajectories By Subject

# %%
# parameters

colormap_traj_params = dict()

# %%
# call the task


colormap_traj = (
    apply_color_map.set_task_instance_id("colormap_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="subject__name",
        output_column_name="subject__name_colormap",
        colormap="tab20b",
        **colormap_traj_params,
    )
    .mapvalues(argnames=["df"], argvalues=skip_map_generation)
)


# %% [markdown]
# ## Rename columns for map tooltip display

# %%
# parameters

rename_display_columns_params = dict()

# %%
# call the task


rename_display_columns = (
    map_columns.set_task_instance_id("rename_display_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "segment_start": "Start",
            "timespan_seconds": "Duration (s)",
            "speed_kmhr": "Speed (kph)",
            "subject__name": "Subject Name",
            "subject__sex": "Subject Sex",
        },
        **rename_display_columns_params,
    )
    .mapvalues(argnames=["df"], argvalues=colormap_traj)
)


# %% [markdown]
# ## Create map layer for each trajectory group

# %%
# parameters

traj_map_layers_params = dict(
    zoom=...,
)

# %%
# call the task


traj_map_layers = (
    create_polyline_layer.set_task_instance_id("traj_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "subject__name_colormap"},
        legend={
            "label_column": "Subject Name",
            "color_column": "subject__name_colormap",
        },
        tooltip_columns=[
            "Start",
            "Duration (s)",
            "Speed (kph)",
            "Nighttime",
            "Subject Name",
            "Subject Sex",
        ],
        **traj_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=rename_display_columns)
)


# %% [markdown]
# ## Draw Ecomaps for each trajectory group

# %%
# parameters

traj_ecomap_params = dict(
    view_state=...,
)

# %%
# call the task


traj_ecomap = (
    draw_ecomap.set_task_instance_id("traj_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={
            "title": "Subject",
            "format_title": False,
            "placement": "bottom-right",
        },
        static=False,
        title=None,
        max_zoom=20,
        widget_id=set_traj_map_title,
        **traj_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=traj_map_layers)
)


# %% [markdown]
# ## Persist ecomap as Text

# %%
# parameters

ecomap_html_urls_params = dict(
    filename=...,
)

# %%
# call the task


ecomap_html_urls = (
    persist_text.set_task_instance_id("ecomap_html_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="v2",
        **ecomap_html_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=traj_ecomap)
)


# %% [markdown]
# ## Create Map Widgets for Trajectories

# %%
# parameters

traj_map_widgets_single_views_params = dict()

# %%
# call the task


traj_map_widgets_single_views = (
    create_map_widget_single_view.set_task_instance_id("traj_map_widgets_single_views")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=set_traj_map_title, **traj_map_widgets_single_views_params)
    .map(argnames=["view", "data"], argvalues=ecomap_html_urls)
)


# %% [markdown]
# ## Merge EcoMap Widget Views

# %%
# parameters

traj_grouped_map_widget_params = dict()

# %%
# call the task


traj_grouped_map_widget = (
    merge_widget_views.set_task_instance_id("traj_grouped_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=traj_map_widgets_single_views, **traj_grouped_map_widget_params)
    .call()
)


# %% [markdown]
# ## Create Dashboard with Subject Tracking Widgets

# %%
# parameters

subject_tracking_dashboard_params = dict()

# %%
# call the task


subject_tracking_dashboard = (
    gather_dashboard.set_task_instance_id("subject_tracking_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[traj_grouped_map_widget],
        groupers=groupers,
        time_range=time_range,
        warning=warn_if_mixed_subtype,
        **subject_tracking_dashboard_params,
    )
    .call()
)
