# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    assign_subject_colors as assign_subject_colors,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope.platform.tasks.warning import (
    mixed_subtype_warning as mixed_subtype_warning,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_bounding_box as get_bounding_box,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_gps_point_filename_prefix as get_gps_point_filename_prefix,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_gps_point_filetypes as get_gps_point_filetypes,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_segment_filter as get_segment_filter,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_skip_relocation_persist as get_skip_relocation_persist,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_track_filename_prefix as get_track_filename_prefix,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_track_filetypes as get_track_filetypes,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_download_params as set_download_params,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_traj_filters as set_traj_filters,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_grouped_dfs_for_results_download as persist_grouped_dfs_for_results_download,
)
from ecoscope_workflows_ext_custom.tasks.skip import invert_bool as invert_bool
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    subject_obs = (
        task(get_subjectgroup_observations)
        .validate()
        .set_task_instance_id("subject_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            **(params.get("subject_obs") or {}),
        )
        .call()
    )

    warn_if_mixed_subtype = (
        task(mixed_subtype_warning)
        .validate()
        .set_task_instance_id("warn_if_mixed_subtype")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(subject_obs=subject_obs, **(params.get("warn_if_mixed_subtype") or {}))
        .call()
    )

    subject_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("subject_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=subject_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    convert_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_to_user_timezone") or {}),
        )
        .call()
    )

    drop_extra_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_to_user_timezone,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix") or {}),
        )
        .call()
    )

    filter_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("filter_obs") or {}),
        )
        .call()
    )

    subject_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("subject_traj") or {}),
        )
        .call()
    )

    drop_extra_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_traj") or {}),
        )
        .call()
    )

    customize_columns_internally = (
        task(map_columns)
        .validate()
        .set_task_instance_id("customize_columns_internally")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_traj,
            rename_columns={},
            drop_columns=["id"],
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("customize_columns_internally") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    relocs_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("relocs_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_obs,
            time_col="fixtime",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("relocs_add_temporal_index") or {}),
        )
        .call()
    )

    split_relocs_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_relocs_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=relocs_add_temporal_index,
            groupers=groupers,
            **(params.get("split_relocs_groups") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=customize_columns_internally,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    customize_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("customize_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            rename_columns={},
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("customize_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    sql_query = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("sql_query")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(sanitize=True, columns=None, **(params.get("sql_query") or {}))
        .mapvalues(argnames=["df"], argvalues=customize_columns)
    )

    download_params = (
        task(set_download_params)
        .validate()
        .set_task_instance_id("download_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("download_params") or {}))
        .call()
    )

    track_filetypes = (
        task(get_track_filetypes)
        .validate()
        .set_task_instance_id("track_filetypes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(params=download_params, **(params.get("track_filetypes") or {}))
        .call()
    )

    track_filename_prefix = (
        task(get_track_filename_prefix)
        .validate()
        .set_task_instance_id("track_filename_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(params=download_params, **(params.get("track_filename_prefix") or {}))
        .call()
    )

    gps_point_filetypes = (
        task(get_gps_point_filetypes)
        .validate()
        .set_task_instance_id("gps_point_filetypes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(params=download_params, **(params.get("gps_point_filetypes") or {}))
        .call()
    )

    gps_point_filename_prefix = (
        task(get_gps_point_filename_prefix)
        .validate()
        .set_task_instance_id("gps_point_filename_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            params=download_params, **(params.get("gps_point_filename_prefix") or {})
        )
        .call()
    )

    relocation_skip = (
        task(get_skip_relocation_persist)
        .validate()
        .set_task_instance_id("relocation_skip")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(params=download_params, **(params.get("relocation_skip") or {}))
        .call()
    )

    skip_relocation_persist = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_relocation_persist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(skip=relocation_skip, **(params.get("skip_relocation_persist") or {}))
        .mapvalues(argnames=["df"], argvalues=split_relocs_groups)
    )

    persist_relocations = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_relocations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            grouped_dfs=skip_relocation_persist,
            filetypes=gps_point_filetypes,
            filename_prefix=gps_point_filename_prefix,
            **(params.get("persist_relocations") or {}),
        )
        .call()
    )

    persist_tracks = (
        task(persist_grouped_dfs_for_results_download)
        .validate()
        .set_task_instance_id("persist_tracks")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            grouped_dfs=sql_query,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filetypes=track_filetypes,
            filename_prefix=track_filename_prefix,
            **(params.get("persist_tracks") or {}),
        )
        .call()
    )

    generate_maps = (
        task(invert_bool)
        .validate()
        .set_task_instance_id("generate_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("generate_maps") or {}))
        .call()
    )

    skip_map_generation = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_map_generation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(skip=generate_maps, **(params.get("skip_map_generation") or {}))
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    set_traj_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_traj_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Subject Group Trajectory Map",
            **(params.get("set_traj_map_title") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    colormap_traj = (
        task(assign_subject_colors)
        .validate()
        .set_task_instance_id("colormap_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            subject_id_column="groupby_col",
            output_column="subject_colormap",
            fallback_strategy="default_color",
            default_color="#FFFF00",
            default_palette="tab20b",
            additional_column="subject__additional",
            **(params.get("colormap_traj") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=skip_map_generation)
    )

    sort_subject_names = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_subject_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="subject__name",
            ascending=True,
            na_position="last",
            **(params.get("sort_subject_names") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=colormap_traj)
    )

    rename_display_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_display_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "segment_start": "Start",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
                "subject__name": "Subject Name",
                "subject__sex": "Subject Sex",
            },
            **(params.get("rename_display_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_subject_names)
    )

    traj_map_layers = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("traj_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "subject_colormap"},
            legend={"label_column": "Subject Name", "color_column": "subject_colormap"},
            tooltip_columns=[
                "Start",
                "Duration (s)",
                "Speed (kph)",
                "Nighttime",
                "Subject Name",
                "Subject Sex",
            ],
            **(params.get("traj_map_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_display_columns)
    )

    traj_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("traj_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Subject",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            title=None,
            max_zoom=20,
            widget_id=set_traj_map_title,
            **(params.get("traj_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=traj_map_layers)
    )

    ecomap_html_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="v2",
            **(params.get("ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=traj_ecomap)
    )

    traj_map_widgets_single_views = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("traj_map_widgets_single_views")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_traj_map_title,
            **(params.get("traj_map_widgets_single_views") or {}),
        )
        .map(argnames=["view", "data"], argvalues=ecomap_html_urls)
    )

    traj_grouped_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("traj_grouped_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=traj_map_widgets_single_views,
            **(params.get("traj_grouped_map_widget") or {}),
        )
        .call()
    )

    subject_tracking_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("subject_tracking_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[traj_grouped_map_widget],
            groupers=groupers,
            time_range=time_range,
            warning=warn_if_mixed_subtype,
            **(params.get("subject_tracking_dashboard") or {}),
        )
        .call()
    )

    return subject_tracking_dashboard
